from enum import Enum

class USER_STATUS(Enum):
    UNKNOWN = 'UNKNOWN'
    UNCONFIRMED = 'UNCONFIRMED'
    CONFIRMED = 'CONFIRMED'
    ARCHIVED = 'ARCHIVED'
    RESET_REQUIRED = 'RESET_REQUIRED'
    FORCE_CHANGE_PASSWORD = 'FORCE_CHANGE_PASSWORD'